[package]
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
name = "sec"
version = "0.1.0"
license = "MIT"
description = "Prevent secrets from leaking via `Debug` or `Display` traits"

[dependencies]
serde = { version ="1.0.24", optional = true }

[features]
default = ["std"]

# the std features enables `String` support, but requires the standard library
std = []

# serde is optional
serialize = ["serde"]
deserialize = ["serde"]
